### ISSUE TITLE
Kill buffers that inherit from other major modes

### ISSUE THREAD

**Issue by shackra** [mrkkrp/kill-or-bury-alive#1]
I was thinking that for the sake of brevity, `kill-or-bury-alive` kill buffers where the major mode inherit from other major modes, for instance:

```
(setf kill-or-bury-alive-must-die-list
          '("^\\*Help\\*$" "^\\*Packages\\*$" dired-mode prog-mode "^\\*Backtrace\\*$"))
```

Many major programming modes inherit from `prog-mode`, so by using `kill-or-bury-alive` in a buffer with `python-mode` it gets killed instead of being buried.

**Comment by mrkkrp** [comment]
`kill-or-bury-alive` just checks symbols representing names of major modes for equality. If I understand you correctly you want `kill-or-bury-alive` to respect inheritance?

**Comment by shackra** [comment]
Less verbosity in my configuration...

El viernes 04 de diciembre del 2015 a las 0155 horas, Mark Karpov escribió:

> Well, this is normal expected behavior. `prog-mode` serves as basis for many other programming modes, I don't think it's ever used by itself. Your config tells the package to kill every buffer with modes that are inherited from `prog-mode` immediately. What exactly you want to achieve?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mrkkrp/kill-or-bury-alive/issues/1#issuecomment-161902968

## 

👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by mrkkrp** [comment]
@shackra, I've pushed necessary changes. If I understood you correctly, this should solve your problem. Now derived modes are recognized, so specifying `prog-mode` will select every programming mode, such as `python-mode` or `emacs-lisp-mode`. Please report here if this works for you.

**Comment by shackra** [comment]
Works awesome!

An observation: Is the code checking `kill-or-bury-alive-long-lasting-list` before killing a
buffer? for instance, let's say that I put "^test.py$" in `kill-or-bury-alive-long-lasting-list`,
since all modes inheriting from `prog-mode` will be killed, included python-mode buffers, will my
test.py be killed or buried?

El jueves 10 de diciembre del 2015 a las 0116 horas, Mark Karpov escribió:

> @shackra, I've pushed necessary changes. If I understood you correctly, this should solve your problem. Now derived modes are recognized, so specifying `prog-mode` will select every programming mode, such as `python-mode` or `emacs-lisp-mode`. Please report here if this works for you.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mrkkrp/kill-or-bury-alive/issues/1#issuecomment-163520921

## 

👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by mrkkrp** [comment]
Why don't you just try it? In this case buffer `test.py` (assuming its major mode is `python-mode`) will be in both “long-lasting” and “must-die” lists, so it will be killed, but you will be asked first to confirm it (because it's a long lasting buffer).

**Comment by shackra** [comment]
I... well... I'm somewhat lazy. That's why I didn't try first 😅

El jueves 10 de diciembre del 2015 a las 2336 horas, Mark Karpov escribió:

> Why don't you just try it? In this case buffer `test.py` (assuming its major mode is `python-mode`) will be in both “long-lasting” and “must-die” lists, so it will be killed, but you will be asked first to confirm it (because it's a long lasting buffer).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mrkkrp/kill-or-bury-alive/issues/1#issuecomment-163845578

## 

👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra
